### ISSUE TITLE
Performance.gov API

### ISSUE THREAD

**Issue by OwenAmbur** [GSA/GSA-APIs#14]
The mapping of the Performance Indicators to the Goals and Objectives is not apparent at http://www.performance.gov/api 

We'd like to transform the data into open, standard, machine-readable StratML format.  http://xml.fido.gov/stratml/index.htm

Doing so would enable agencies to comply with section 10 of the GPRA Modernization Act (GPRAMA).  http://xml.fido.gov/stratml/references/PL111-532StratML.htm#SEC10

**Comment by jcastle** [comment]
@OwenAmbur, sorry for the delay.  Is this issue still relevant?  I can run down the team and get this issue to them.

**Comment by OwenAmbur** [comment]
Yes, since the Performance.gov site is being reengineered, this issue is not only still relevant but also very timely.  

See also https://gcn.com/articles/2017/05/10/machine-readable-data.aspx
