### ISSUE TITLE
Add the api.data.gov api 

### ISSUE THREAD

**Issue by gbinal** [GSA/GSA-APIs#15]
http://api.data.gov/developer/

**Comment by rdgsa** [comment]
Add to which site?

**Comment by gbinal** [comment]
www.gsa.gov/developer, a.k.a. http://open.gsa.gov/developer/.

**Comment by gbinal** [comment]
I can file a PR.  I don't know why I didn't at the time.

**Comment by rdgsa** [comment]
Hold off for now. We're moving all those issues over to the redesign site
(hackathon next Friday).

https://github.com/GSA/open-gsa-redesign





Ryan Day | IT Specialist | GSA Digital Service (detail) | GSA IT
Office: 816-823-5322 | Mobile: 816-206-9534 | ryan.day@gsa.gov

**Comment by gbinal** [comment]
Sure thing.

**Comment by rdgsa** [comment]
Moved to redesign repo for developers page:

https://github.com/GSA/open-gsa-redesign/issues/36
