### ISSUE TITLE
How current is the data that is returned from SAM?

### ISSUE THREAD

**Issue by saintcyr** [GSA/GSA-APIs#3]
If an entity user made a change at 9:00 am ET on SAM, how soon will this update be available via the API? In other words, how current is the data being returned from SAM?

**Comment by saintcyr** [comment]
Following up to see if the SAM Web service will be more "live" in the near future. We are particularly interested in the exclusion flag.

**Comment by jcastle** [comment]
@saintcyr, I recommend you inquiring with the SAM team at https://github.com/GSA/sam_api/issues.
