### ISSUE TITLE
Data.gov Top 10 Visiting States - missing state column

### ISSUE THREAD

**Issue by edsu** [GSA/GSA-APIs#30]
The [Data.gov Top 10 Visiting States - Archival](https://inventory.data.gov/dataset/2f3fa83b-80f3-4951-8ef7-96e213a53c16/resource/48dc3ad1-ebb0-4ee8-993a-defa131af5e2/) dataset linked to from [here](http://open.gsa.gov/data/#theme-Information Technology) is lacking data in the state column.

**Comment by jcastle** [comment]
@edsu 

This is somewhat dated and I apologize if no one has responded.

I recommend moving this issue to the SAM API repo - https://github.com/GSA/data.gov/issues.
