### ISSUE TITLE
Error 21

### ISSUE THREAD

**Issue by boadiljones** [GSA/GSA-APIs#31]
Im getting this error event when i'm sending the coredata=Y and startDate and Enddate
Basic Error: Invalid search criteria.At least one search criteria element is required

Thoughts?

**Comment by jcastle** [comment]
@boadiljones 

This is dated, I apologize if no one has responded.  Can you tell me what API or app this is reference to?  I want to point you in the right direction.

One option is to look at open.gsa.gov/api or github/gsa.  Thanks!

**Comment by jcastle** [comment]
Closing based on timeframe.  If still needed, please respond with details.
