### ISSUE TITLE
Find a registration by DUNS returns "not found" (404) error for inactive DUNS

### ISSUE THREAD

**Issue by craigeddy** [GSA/GSA-APIs#32]
For example:

https://api.data.gov/sam/v3/registrations/2494664420000?&api_key=DEMO_KEY

The DUNS has data, found by searching on SAM.gov. However this URL does not work.

Is it possible to retrieve the full registration info for an inactive DUNS?

Thanks,
Craig Eddy
eddycr@state.gov
Department of State, Office of Foreign Assistance Resources

**Comment by nvembar** [comment]
Craig, can you cross post this question to the SAM API Git - https://github.com/GSA/sam_api. You'll be able to get a response from @aromero6 and the team.

**Comment by craigeddy** [comment]
My apologies....thought that's where I was :)

**Comment by jcastle** [comment]
Recommend moving this issue to the SAM API repo - https://github.com/GSA/sam_api/issues.
