### ISSUE TITLE
broken link for MyUSA Citizen API (https://my.usa.gov/developer/) 

### ISSUE THREAD

**Issue by diginet-md** [GSA/GSA-APIs#33]
Good evening 
1) pls. visit page 
http://open.gsa.gov/developer/
2) look MyUSA Citizen API 
2.1 link https://my.usa.gov/developer/ is broken 
RGRDS

**Comment by rdgsa** [comment]
Thank you for reporting this. Those links have been removed.

Full background here:
https://github.com/GSA/open.gsa.gov/issues/58
