### ISSUE TITLE
search by city

### ISSUE THREAD

**Issue by thetif** [GSA/GSA-APIs#34]
I am trying to use the SAM API to get all of the HUBZone companies in the Baltimore metro area. When I search by Baltimore, it only gives me the companies with an address specifically in Baltimore. The metro has more than 50 cities in it. Do I have to search by each city specifically or is there another field I could use? Is there anyway to search by SBA office code? I know you guys don't pull office code from SBA, but it would be great if you did and we could search on it.

**Comment by aromero6** [comment]
Hi @thetif 
I know we report back on county codes, which would help in your case, but I am not positive if that is a searchable field.  I have asked our development team to clarify if there is a viable solution at this time for you and what we can do for a feature request if there isn't a solution.
Thanks,
Tony

**Comment by thetif** [comment]
Thanks so much.

**Comment by jcastle** [comment]
Recommend moving this issue to the SAM API repo - https://github.com/GSA/sam_api/issues.
