### ISSUE TITLE
hasKnownExclusions Bug

### ISSUE THREAD

**Issue by rehabprodirect** [GSA/GSA-APIs#35]
There is a bug for the hasKnownExclusions field.
If you use a DUNS number from any contracting company that has exclusions, the API still displays false. I used the SAM Database to get different DUNS numbers for contractors with and without exclusions, and in the JSON file the API produces it always comes up as false.

**Comment by jcastle** [comment]
Recommend moving this issue to the SAM API repo - https://github.com/GSA/sam_api/issues.
