### ISSUE TITLE
Using V3 in SAM search API

### ISSUE THREAD

**Issue by badawyhisham** [GSA/GSA-APIs#36]
I tried to use V3 in SAM search API ,but it didn't work.
For example https://api.data.gov/sam/v1/registrations?qterms=GSA&api_key=DEMO_KEY
I used v3 insread of v1 but I got error message.

**Comment by joescript** [comment]
I also am unable to access V3 OR V4 -- are they up?

**Comment by jcastle** [comment]
Recommend moving this issue to the SAM API repo - https://github.com/GSA/sam_api/issues.
