### ISSUE TITLE
Historical Entity Data

### ISSUE THREAD

**Issue by HerschelC** [GSA/GSA-APIs#38]
Is there a way, if not, please add as a request to:

I'd like to perform a search for an entity based upon a particular point in time.  For example, on March 1, 2016 was this entity classified as a small business (or 8a or HUBZone or ...).  

Creating mashups with changing entity data requires that we know what the entity looks like at a particular point in time.  I execute a search today (March 4, 2016) on an entity and it indicates that the entity is not 8a.  However what I am investigating is related to an earlier date when the entity may have been an 8a.  How do we get a snapshot of an entity from SAM at a given point in time rather than just what it happens to be today?

**Comment by saintcyr** [comment]
Hello. I don't have an answer for you but I'm checking in to see if you received a response on another channel or if you were able to find a solution.

**Comment by jcastle** [comment]
Recommend moving this issue to the SAM API repo - https://github.com/GSA/sam_api/issues.
