### ISSUE TITLE
How current is the data returned by the SAM API? 

### ISSUE THREAD

**Issue by saintcyr** [GSA/GSA-APIs#39]
We currently use the download extract from SAM, but our preference would be to get access to "real time" data especially when it comes time to verify if an entity has a SAM registration. As I understand it, the data may be 12 hours or more old.  In time-sensitive situations, it would be very helpful to the user if we can access their registration status at the moment that we do the verification.

**Comment by jcastle** [comment]
Recommend moving this issue to the SAM API repo - https://github.com/GSA/sam_api/issues.
