### ISSUE TITLE
Keeping a local SAM list synched to master

### ISSUE THREAD

**Issue by joescript** [GSA/GSA-APIs#41]
Folks, We want to use the API to keep a local copy of the SAM data in synch with the Government's. We can obviously download the monthly files. But what we're looking for is a simple search semantic via the API:

"give me everything I don't have"

This would easily be accomplished by adding a last_update_date to each record in the SAM database. Then I can query "where last_update_date > max(last_update_date in my replica).

**Comment by jcastle** [comment]
Recommend moving this issue to the SAM API repo - https://github.com/GSA/sam_api/issues.
