### ISSUE TITLE
Trying to use V2 search on updateDate

### ISSUE THREAD

**Issue by joescript** [GSA/GSA-APIs#42]
According to the docs, this is supported in search V2:

https://api.data.gov/sam/v2/registrations?qterms=updateDate:[2015-01-01,2015-05-05]&api_key=...

I'm getting this in response:

{"Message":"One or more invalid search field(s). ', updateDate' is not a valid search field(s). Please resolve and resubmit your search. You may reference the SAM API Documentation at http://gsa.github.io/sam_api/sam/search.html for a list of valid search fields.","Code":400,"Error":"Bad Request"}

Can you provide any guidance? Thanks

**Comment by jcastle** [comment]
Recommend moving this issue to the SAM API repo - https://github.com/GSA/sam_api/issues.
