### ISSUE TITLE
What happens when the rate limit is surpassed? 

### ISSUE THREAD

**Issue by mattacors** [GSA/GSA-APIs#43]
Hello. I read that the rate limits for the API are currently 5,000 calls per 24 hours and 5 calls per 5 seconds. What happens when that is exceeded? It there a way to get more calls per 24 hours? Is there a certain price you have to pay to get more? Thank you.

**Comment by rdgsa** [comment]
Can you provide a little more background? Are you referring to a specific API? If you could share the page that you're referring to it would help.

**Comment by mattacors** [comment]
@rdgsa sure thing. I am referring to the SAM API https://gsa.github.io/sam_api/sam/ .

**Comment by mattacors** [comment]
Any assistance would be appreciated, thanks!

**Comment by mattacors** [comment]
Following up on this.

**Comment by mattacors** [comment]
We are looking to prioritize this and any feedback would be appreciated.

**Comment by jcastle** [comment]
Recommend moving this issue to the SAM API repo - https://github.com/GSA/sam_api/issues.

**Comment by jcastle** [comment]
BTW, I have had one other consumer discuss this issue.  Believe the output rate is being limited.
