### ISSUE TITLE
Data discrepancies between the SAM web site and the web service

### ISSUE THREAD

**Issue by kpotts1026** [GSA/GSA-APIs#45]
Per the attached document, we are receiving data discrepancies between the web site and the web service. The top of the form shows the data returned when we query a facility. The data highlighted in red does not match between the web service/API query vs. the manual web site query. The bottom of the form shows the data returned when we query a provider with the discrepancies highlighted in red also. We need to verify the validity of the data, which should match between the web site and the web service.
[SAM Web Service Issue.pdf](https://github.com/GSA/GSA-APIs/files/893696/SAM.Web.Service.Issue.pdf)

**Comment by jcastle** [comment]
Recommend moving this issue to https://github.com/GSA/sam_api/issues.
