### ISSUE TITLE
API/Web Service Issue

### ISSUE THREAD

**Issue by ikennanwankpa** [GSA/GSA-APIs#48]
Hi,

I am experiencing an issue with the API/web service that produces the following error message whenever my system attempts to validate the DUNS number entered with the SAM database. Is there a technical individual that can work with my developers to resolve this issue so that organizations can continue to use our grants management system? 

There have not been any development changes on my end so we do not know why the web service is all of a sudden not working. Thanks.

Ikenna N. 

**

> Unexpected error:Error Code: 3454636

**

**Comment by rdgsa** [comment]
Hello, the SAM API is supported through issues in this repo:

https://github.com/GSA/sam_api/issues

I recommend that you post your issue over there.

**Comment by ikennanwankpa** [comment]
Thank you!
