### ISSUE TITLE
Request for increase in API key and IP rate limits

### ISSUE THREAD

**Issue by hessc99** [GSA/GSA-APIs#49]
We are a Federal Government contractor developing an application that uses and sam.gov data and request an increase in API key and IP address limits.  I can provide additional details and justification via non-public channels.  Thanks,

**Comment by rdgsa** [comment]
Please post that issue in the SAM API issues for the best support:

 https://github.com/GSA/sam_api/issues

**Comment by hessc99** [comment]
Thank you.
