### ISSUE TITLE
Add a notifications option

### ISSUE THREAD

**Issue by gbinal** [GSA/GSA-APIs#5]
Use GitHub Issues to create an issue that you lock and tell people to follow for updates about GSA APIs.

**Comment by rdgsa** [comment]
Another option for this would be a blog page on open.gsa.gov. This is one of the project hypotheses for the site redesign.  
https://github.com/GSA/open-gsa-redesign/wiki/Project-hypotheses

**Comment by jcastle** [comment]
Completed with issue #46
