### ISSUE TITLE
FBO API live?

### ISSUE THREAD

**Issue by prasadh13** [GSA/GSA-APIs#50]
Is there a FBO data source to consume? The FBOpen API seems to be deprecated. Any alternative RESTFul source?

**Comment by Ryandaydev** [comment]
The REST API has been decommissioned, but FBO information is available through a SOAP webservice. The documentation is available here:
https://www.fbo.gov/?s=generalinfo&mode=list&tab=list&tabmode=list&static=documentation

**Comment by Ryandaydev** [comment]
Closing this issue.
