### ISSUE TITLE
Integrate FPDS web service

### ISSUE THREAD

**Issue by baskerGanesan** [GSA/GSA-APIs#51]
Hello, I am trying to integrate FPDS web service in .Net to access the data but I could not find wsdl link anywhere?

Can you please help me out for web service address

**Comment by Ryandaydev** [comment]
Information about using the webservice is available here:
https://www.fpds.gov/fpdsng_cms/index.php/en/worksite.html

The latest version of the webservice specification is 1.5: 
https://www.fpds.gov/downloads/FPDS-Specifications-WebServices_Integration_Specifications_V1.5.doc
