### ISSUE TITLE
FPDS API - Missing Data

### ISSUE THREAD

**Issue by jillmakr** [GSA/GSA-APIs#54]
Previously available fields in the FPDS API seem to not be populating anymore - Annual Revenue and Employee Count in the contractor data.  

We pull these fields for use in discovery.gsa.gov and are currently failing deployment tests as a result of the missing data.

Was this data intentionally removed?  Need to know if we need to update the site. 

(Also submitted tickets to data.gov and federal service desk for reference)

**Comment by Ryandaydev** [comment]
@jillmakr Reach out to me and I can share the internal POCs for that API.
