### ISSUE TITLE
Per Diem Rates API - Not all zip codes have meal data

### ISSUE THREAD

**Issue by RiceRiceBaby** [GSA/GSA-APIs#58]
I ran the State/Fiscal Year API for all the states for fiscal 2019. There were a large number of records that did not contain an amount for meals. For those records that do not have meals, what is their amount supposed to be? Is there any way you guys can display a value for meals for every record instead of just some records?

**Comment by Ryandaydev** [comment]
Thanks. Would you be able to post an example?

**Comment by RiceRiceBaby** [comment]
https://inventory.data.gov/api/action/datastore_search?resource_id=8ea44bc4-22ba-4386-b84c-1494ab28964b&limit=300000&filters={"FiscalYear":"2019","State":"AL"}

You will see that alot of records contains meals, and alot of records do not contain meals.
