### ISSUE TITLE
Per DIem API Data contains a bunch of rates in records that contain no city, county, state, or zip

### ISSUE THREAD

**Issue by RiceRiceBaby** [GSA/GSA-APIs#59]
Per DIem API Data contains a bunch of rates in records that contain no city, county, state, or zip. I don't understand what these records are for. I need to run your api to ingest data into our database to use for per diem calculations, but i'm not sure what these empty records are for.

**Comment by Ryandaydev** [comment]
@RiceRiceBaby Thank you for bringing this to our attention. Would you mind identifying a couple of examples so we can look into your question?
