### ISSUE TITLE
Forecast of Contracting Opportunities API returns 403

### ISSUE THREAD

**Issue by natenash203** [GSA/GSA-APIs#60]
Based on the documentation provided for the [Acquisition Gateway API](https://hallways.cap.gsa.gov/docs/#/api) , the GET /osbu-opportunities endpoint appears to return a 403. I couldn't find any info in the docs regarding auth and it appears this is public data. Any thoughts?

Request:
GET https://hallways.cap.gsa.gov/api/v1.0/osbu-opportunities

Response:
`{
    "type": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.4",
    "title": "Access denied.",
    "status": 403,
    "detail": "Forbidden."
}`

**Comment by PeterNguyen-GSA** [comment]
Hello, This specific endpoint requires authentication.  However, we're working to update the Gateway API document to allow data samples to be consumed/displayed where applicable.  We'll update here when the documentation updated.
