### ISSUE TITLE
The domain api.usa.gov is unavailable and down!

### ISSUE THREAD

**Issue by praneethk19** [GSA/GSA-APIs#65]
I'm not able to access the FBI Crime Data API. The domain is down for a very long time.

**Comment by Ryandaydev** [comment]
> I'm not able to access the FBI Crime Data API. The domain is down for a very long time.

I believe you are asking about an FBI API. It looks like you can get more information and support that API here: https://crime-data-explorer.fr.cloud.gov/api

**Comment by praneethk19** [comment]
For your information, I'm already using the same API.

**Comment by gbinal** [comment]
Thanks, @PraneethKarnena.  We've also sent an email to the team over there to make sure they're aware of this.

**Comment by praneethk19** [comment]
@gbinal The URL is in fact been up all the time! The issue is with my DNS, OpenDNS. I have changed it to Google DNS and everything is just fine. Thank You! 🙂
