### ISSUE TITLE
Zipcode and Fiscal year endpoint returns wrong state

### ISSUE THREAD

**Issue by devkccarp** [GSA/GSA-APIs#68]
Winchester, Va returns state as "MA"
https://api.gsa.gov/travel/perdiem/v2/rates/zip/22602/year/2019
Kearneysville, WV returns state as "MA"
https://api.gsa.gov/travel/perdiem/v2/rates/zip/25430/year/2019

**Comment by ironmac34** [comment]
I am seeing this too.
Haven't checked all, but looking at the above zip codes and this one below, it could be that anything referencing back to the standard per-diem rate is defaulting to the wrong state, as well as not populating the county, or displaying a correct city name.

https://api.gsa.gov/travel/perdiem/v2/rates/zip/62034/year/2020

**Comment by devkccarp** [comment]
This issue has been resolved. 

@ironmac34 when the standard rate is returned, the county and state are never returned. I believe this is by design as the old API at inventory.data.gov was the same way. At least with the Fiscal Year and Zipcode endpoints.

I had success getting this issue resolved by contacting the maintainer listed here: https://catalog.data.gov/dataset/per-diem-api 

They were responsive and quick to make the changes in order to fix this issue. Good luck.

**Comment by adborden** [comment]
@ironmac34 you should open a new issue if that behavior is needed.
