### ISSUE TITLE
hyperlink URLs in documentation

### ISSUE THREAD

**Issue by gbinal** [GSA/GSA-APIs#7]
For each of the below APIs, there are a bunch of example URLs that aren't hyperlinked.  It's a small thing but it'd be good to hyperlink the text of those URLS with the URL.  
- http://www.usa.gov/About/developer-resources/corporation-contact-directory/index.shtml
- http://www.usa.gov/About/developer-resources/federal-agency-directory/index.shtml
- https://go.usa.gov/api

cc @smileytech

**Comment by jcastle** [comment]
Recommend posting this issue in https://github.com/usagov/usa.gov/issues.
