### ISSUE TITLE
Example URL incorrect

### ISSUE THREAD

**Issue by random1781** [GSA/GSA-APIs#74]
The hyperlink provided immediately upon requesting an API key in the 'Getting Started' section is incorrect and clicking on it result in a NOT_FOUND error. It is currently:

https://api.gsa.gov/travel/perdiem/rates/city/....

It should be:

https://api.gsa.gov/travel/perdiem/v2/rates/city/....

**Comment by Ryandaydev** [comment]
This has been corrected, thanks for notifying us.
