### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by datocrats-org** [GSA/GSA-APIs#75]
I need to retrieve the latest API documentation for multiple GSA APIs, e.g., SAM. I am using Postman. I doubt any developer will find the web pages describing of the APIs useful without an automated approach.  I was referred from http://gsa.github.io/sam_api/sam/console/#!/sam_swagger.json to view the API documentation at https://raw.githubusercontent.com/GSA/sam_api/gh-pages/static/api_docs/sam_swagger.json 

I later found a stackoverflow tip suggesting I could edit the URL to get the latest JSON - https://api.data.gov/sam/v8/api-docs?group=App?api_key=***** but that is not working, may be misformatted or blocked.  

I would prefer you publish using the latest OpenAPI format, 2.0, also.

**Comment by Ryandaydev** [comment]
Here are the instructions for getting assistance with this API, from this page:
http://gsa.github.io/sam_api/sam/issues.html

**Getting Help with SAM API or Web Service**
If you experience difficulty or have questions, your best course is to contact the Federal Service Desk (www.fsd.gov) and open a service ticket. This will get you funneled to the correct technical team who can troubleshoot and help you resolve any issues you may have.

**Comment by datocrats-org** [comment]
fsd.gov referred me here - they said they don't know what has been shifted to them
