### ISSUE TITLE
API Question (entity information)

### ISSUE THREAD

**Issue by mbasqu01** [GSA/GSA-APIs#78]
Hi, I'm interested in downloading entity information via the API. I'm doing some research on the open.gsa.gov site to learn about the API and was a little unsure about this section (on https://open.gsa.gov/api/entity-api/): 

**Key Features of the Entity Management API:**
- It offers several optional search parameters, filtering by sections, AND, OR, NOT conditions and a free text search q to obtain the desired data.
- It returns synchronous responses directly in the browser.
- It returns ten records per page in the JSON format.
- It can return only the first 10,000 records.

**Additional Features of the Entity Management API:** It can serve as an Extract API with the addition of “format” parameter in the request. Following are the key features of the Entity Management Extract API:
- It offers several optional search parameters, filtering by sections, AND, OR, NOT conditions and a free text search q to obtain the desired data.
- It returns asynchronous responses by sending file downloadable links in the browser and in the user emails.
- It returns data in the JSON or CSV format as selected by the user.
- It can return only the first 1,000,000 records.

Does the second section of bullet points pertain only to queries that include the format parameter? If so, it looks like that increases the limit from 10k to 1M, which I think would mean you could theoretically download all entity information? Is that correct? Also, does the lastUpdateDate field capture the last date anything for an entity changed in your system? I'm thinking once I create a query for entities I care about, if I add a lastUpdateDate criteria with the date of my last query run, that would return any new entities as well as any changes that have occurred to entities I had already pulled?

**Comment by Ryandaydev** [comment]
Hello, to get support for this API, please go to the Federal Service Desk (www.fsd.gov) and open a ticket. They will be able to track your question and respond.

**Comment by mbasqu01** [comment]
I first contacted the beta.sam site who referred me to FSD who then referred me to this site.
