### ISSUE TITLE
make the interactive documentation more prominent

### ISSUE THREAD

**Issue by gbinal** [GSA/GSA-APIs#8]
Interactive documentation is great for developers but on both of the below APis, it's virtually buried and very easy to miss.  I'd suggest integrating it direction into the pages linked below and not linked off from there!  
- http://www.usa.gov/About/developer-resources/corporation-contact-directory/index.shtml
- http://www.usa.gov/About/developer-resources/federal-agency-directory/index.shtml

**Comment by jcastle** [comment]
Recommend posting this issue in https://github.com/usagov/usa.gov/issues.
