### ISSUE TITLE
API for top and/or trending search terms

### ISSUE THREAD

**Issue by jedsundwall** [GSA/GSA-APIs#9]
USA.gov should create an API that exposes the daily top (10? 20? 50?) search queries it receives each day. This data could help agencies provide better services to the public by giving them more insight into what the public is seeking out. It could also be useful to congress as well as media companies that might be able to create content based on insights from the data.

A separate API could be used for search terms that aren't at the top of the list, but have grown extremely quickly, similar to how [bitly's "bursting_phrases" API](http://dev.bitly.com/data_apis.html#v3_realtime_bursting_phrases) work.

Due to privacy concerns, no search terms should be revealed unless they have been searched by a certain number (50?) of unique IP addresses.

**Comment by jcastle** [comment]
@jedsundwall, sorry for the delay.  Is this still relevant to you?  I can try to run down someone from the program office to get a response.
